services:
  web:
    image: gc
    container_name: tasks-NodeJS
    restart: always
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - MONGO_URI=${MONGO_URI}
    networks:
      - devops-network

networks:
  devops-network:
    external: true

